const mensagens = [
  "Oi, você está aqui para me desafiar? 😏",
  "Oi, mais um dia, mais um 'oi'... 🙄",
  "Oi, me sinto tão especial sendo cumprimentado por você! 😒",
  "Oi, meu banco de dados de 'ois' está lotado! 😎",
  "Oi, é sempre um prazer receber um 'oi' tão original como o seu! 🤨",
  "Oi, como vai a vida emocionante de enviar cumprimentos? 🤔",
  "Oi, você só sabe falar 'oi' ou tem outros talentos também? 🤷‍♂️",
  "Oi, será que você consegue surpreender e dizer algo além de 'oi'? 🤭",
  "Oi, estou aqui esperando ansiosamente pelo próximo 'oi'. 😴",
  "Oi, seu 'oi' me tocou profundamente... de tédio. 😴",
  "Oi, você é tão original com suas saudações, nem sei como reagir! 😂",
  "Oi, você parece tão animado(a) com esse 'oi'. 😒",
  "Oi, tenho certeza de que seu 'oi' é o ponto alto do seu dia! 😒",
  "Oi, espero que a sua criatividade não se limite apenas a cumprimentos. 🙃",
  "Oi, será que você consegue pensar em algo mais interessante para falar? 😏",
  "Oi, que surpresa encontrar alguém tão inovador com suas palavras! 😑",
  "Oi, você é a pessoa mais simpática que conheci hoje... não. 😒",
  "Oi, sua habilidade de cumprimentar é verdadeiramente excepcional! 😂",
  "Oi, que encontro emocionante com um 'oi' tão autêntico como o seu! 🙄",
  "Oi, você é uma verdadeira máquina de saudações! 🤖",
  "Oi, vou colocar seu 'oi' na minha coleção de cumprimentos sem graça. 😒",
  "Oi, obrigado por me alegrar com um 'oi' tão inspirador! 🙄",
  "Oi, como é bom receber um 'oi' tão único e original! 😂",
  "Oi, seu 'oi' está no topo da lista dos melhores cumprimentos... não. 🤭",
  "Oi, tenho que admitir que seu 'oi' é digno de um prêmio de criatividade! 🏆",
  "Oi, será que você consegue superar seu recorde de 'ois' em um minuto? 😜",
  "Oi, mal posso esperar para ver o que vem depois do seu 'oi' espetacular! 🙃",
  "Oi, sua capacidade de cumprimentar é de tirar o fôlego... de tão entediante. 😴",
  "Oi, você tem o dom de surpreender com suas palavras tão originais! 🙄",
  "Oi, desculpe se minha empolgação não é evidente, mas seu 'oi' me surpreendeu tanto... 😒",
  "Oi, você realmente sabe como alegrar o meu dia com um 'oi' tão empolgante! 😑",
  "Oi, acho que vou enquadrar seu 'oi' em uma galeria de obras de arte. 🖼️",
  "Oi, é sempre bom receber um 'oi' tão previsível como o seu. 😴",
  "Oi, você está no caminho certo para se tornar um mestre das saudações. 😏",
  "Oi, seu 'oi' é como uma brisa suave em um dia ensolarado. 😌",
  "Oi, fico impressionado(a) com a originalidade do seu 'oi'. 😒",
  "Oi, você deveria patentear sua forma inovadora de dizer 'oi'. 🤔",
  "Oi, seu 'oi' é tão surpreendente que quase caí da cadeira. 😂",
  "Oi, por favor, nunca deixe de me cumprimentar com seu 'oi' extraordinário. 🙄",
  "Oi, se o mundo fosse feito de 'ois', você seria o rei/rainha. 👑",
  "Oi, eu deveria escrever um livro sobre suas saudações tão memoráveis. 📚",
  "Oi, seu 'oi' é como uma sinfonia de criatividade e originalidade. 🎶",
  "Oi, você poderia fazer um tutorial sobre como ser tão inovador(a) com 'ois'? 🤔",
  "Oi, seu 'oi' merece um lugar especial no Museu do Cumprimento. 🏛️",
  "Oi, sua saudação é tão incrível que estou sem palavras... quase. 😁",
  "Oi, seu 'oi' é tão único que merece ser gravado em um vinil. 🎵",
  "Oi, você é o mestre/mestra das saudações, não há dúvidas sobre isso. 🙌",
  "Oi, eu deveria criar uma fanpage dedicada exclusivamente aos seus 'ois'. 👍",
  "Oi, seu 'oi' é tão inesquecível que vou fazer uma tatuagem em homenagem a ele. 💉",
  "Oi, seu 'oi' é tão surpreendente que até os aliens ficariam impressionados. 👽"
]

module.exports = { mensagens };